name: Deployment Pipeline

on: 
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: E2E Test
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm run start-test
          wait-on: http://localhost:5000/
          command: npm run test:e2e
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true