name: Deployment Pipeline

on: 
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint